/**
 * Demo snapshot for design iteration + screenshots. Loaded only when the page is
 * opened with `?mock` (see ws.svelte.ts) — dynamically imported so it stays out of
 * the main bundle in normal use.
 */
import type { Snapshot } from "./types";

export const MOCK: Snapshot = {
  type: "snapshot",
  provider: { model: "qwen3.5:9b", baseUrl: "http://localhost:11434/v1", ok: true },
  budget: { turns: 142, maxTurns: 300, minutes: 88, maxMinutes: 240, exceeded: false },
  settings: {
    providerModel: "qwen3.5:9b",
    providerBaseUrl: "http://localhost:11434/v1",
    maxConcurrent: 2,
    budget: { maxTurns: 300, maxMinutes: 240 },
    defaults: { permissionMode: "acceptEdits", autonomy: "balanced" },
  },
  sessions: [
    {
      id: "refactor-db",
      cwd: "C:\\dev\\core",
      goal: "Migrate the data layer from raw SQL to the query builder.",
      doneCriteria: "all queries migrated, tests green",
      permissionMode: "default",
      autonomy: "cautious",
      mode: "autopilot",
      status: "needs-input",
      turns: 7,
      elapsedMin: 12.0,
      lastReply: "",
      lastDecision: "⚠ risky gate: rm -rf ./legacy",
      attention: {
        kind: "gate",
        question: "Claude wants to run: rm -rf ./legacy — delete the legacy SQL folder?",
        options: [
          { label: "Approve once", rationale: "folder is committed to git, recoverable" },
          { label: "Deny", rationale: "keep it for reference this run" },
        ],
      },
    },
    {
      id: "api-server",
      cwd: "C:\\dev\\api",
      goal: "Build the REST API with auth, rate limiting, and OpenAPI docs.",
      doneCriteria: "endpoints pass integration tests",
      permissionMode: "acceptEdits",
      autonomy: "balanced",
      mode: "autopilot",
      status: "running",
      turns: 23,
      elapsedMin: 41.2,
      lastReply: "",
      lastDecision: "continue → wire the /auth refresh-token endpoint and add a test",
      attention: null,
    },
    {
      id: "docs-site",
      cwd: "C:\\dev\\docs",
      goal: "Write and polish the documentation site with examples.",
      doneCriteria: "all pages drafted",
      permissionMode: "acceptEdits",
      autonomy: "autonomous",
      mode: "autopilot",
      status: "running",
      turns: 11,
      elapsedMin: 18.7,
      lastReply: "",
      lastDecision: "continue → add a quickstart code sample to the landing page",
      attention: null,
    },
    {
      id: "mobile-ui",
      cwd: "C:\\dev\\app",
      goal: "Implement the onboarding flow screens in React Native.",
      doneCriteria: "3 screens built",
      permissionMode: "default",
      autonomy: "balanced",
      mode: "manual",
      status: "manual",
      turns: 4,
      elapsedMin: 6.3,
      lastReply: "",
      lastDecision: "",
      attention: null,
    },
    {
      id: "data-pipeline",
      cwd: "C:\\dev\\etl",
      goal: "Build the nightly ETL job and add monitoring.",
      doneCriteria: "job runs end to end",
      permissionMode: "default",
      autonomy: "balanced",
      mode: "autopilot",
      status: "queued",
      turns: 0,
      elapsedMin: 0,
      lastReply: "",
      lastDecision: "queued — waiting for a free slot",
      attention: null,
    },
    {
      id: "landing-page",
      cwd: "C:\\dev\\www",
      goal: "Ship the marketing landing page and hook up analytics.",
      doneCriteria: "deployed to prod",
      permissionMode: "acceptEdits",
      autonomy: "balanced",
      mode: "autopilot",
      status: "done",
      turns: 31,
      elapsedMin: 52.9,
      lastReply: "",
      lastDecision: "stopped: goal met — landing page deployed",
      attention: null,
    },
  ],
  focus: {
    id: "api-server",
    screen: [
      "> Added refresh-token rotation to src/auth/tokens.ts and a regression",
      "  test in tests/auth.spec.ts.",
      "",
      "● Running 14 tests…",
      "  ✓ issues a refresh token on login",
      "  ✓ rotates the token on refresh",
      "  ✓ rejects a reused token",
      "",
      "All tests passing. Ready for the next step.",
    ].join("\n"),
  },
};
